[package]
version = "1.1.10"
authors = ["dbataille@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["event", "layer", "manager", "copy", "camera", "capture"]
title = "Lightspeed Event Copy Capture Perspertive to Perspertive"
description = "Lightspeed Event that will copy the perspertive camera from the capture layer to the regular perspertive"
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"

[dependencies]
"lightspeed.common" = {}
"lightspeed.events_manager" = {}
"lightspeed.layer_manager.core" = {}
"lightspeed.trex.utils.common" = {}
"omni.flux.utils.common" = {}
"omni.usd" = {}

[[python.module]]
name = "lightspeed.event.capture_persp_to_persp"

[[test]]
args = [
    # "--/renderer/mdl/searchPaths/templates=${kit}/../omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
    # For what ever reason, using the command line directly will not resolve ${kit} for mdl path.
    # Need to use a .kit file
    "--merge-config=${app}/../../exts/lightspeed.trex.app.resources/data/tests/lightspeed.trex.app.resources.core_material.kit"
]

dependencies = [
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.capture.core.shared",
    "lightspeed.trex.viewports.shared.widget",  # grab the viewport because the viewport generate the persp camera
    "lightspeed.trex.viewports.stagecraft.bundle",  # grab the viewport because the viewport generate the persp camera
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.scene_view.opengl] No UsdRender.Product was found at '{render_product_path}'*",
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
