[package]
title = "Extension example to create the core"
description = "This is an event for setting the camera light"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
version = "1.0.3"
authors = [ "Shona Gillard <sgillard@nvidia.com>",]
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.event.camera_light"
category = "internal"
keywords = [ "remix", "event"]
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"lightspeed.events_manager" = {}
"omni.flux.utils.common" = {}
"lightspeed.trex.asset_replacements.core.shared" = {}
"lightspeed.hydra.remix.core" = {}

[[python.module]]
name = "lightspeed.event.camera_light"

[[test]]
dependencies = [
    "lightspeed.trex.capture.core.shared",
    "lightspeed.trex.tests.dependencies",
    "lightspeed.trex.viewports.shared.widget",  # grab the viewport because the viewport generate the persp camera
    "lightspeed.trex.viewports.stagecraft.bundle",  # grab the viewport because the viewport generate the persp camera
]

args = [
    # "--/renderer/mdl/searchPaths/templates=${kit}/../omni_core_materials/Base;${kit}/mdl/core/Base;${kit}/mdl/core/Volume;${kit}/mdl/core/mdl"
    # For what ever reason, using the command line directly will not resolve ${kit} for mdl path.
    # Need to use a .kit file
    "--merge-config=${app}/../../exts/lightspeed.trex.app.resources/data/tests/lightspeed.trex.app.resources.core_material.kit"
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.scene_view.opengl] No UsdRender.Product was found at '{render_product_path}'*",
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
