[package]
authors =["Damien Bataille <dbataille@nvidia.com>"]
title = "NVIDIA RTX Remix workfile menu"
description = "Workfile menu to save/save as workfile for NVIDIA RTX Remix App"
version = "1.2.1"
readme = "docs/README.md"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/-/tree/main/source/extensions/lightspeed.trex.menu.workfile"
category = "internal"
keywords = [ "remix",]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.widget.prompt" = {}
"omni.kit.window.preferences" = {}
"omni.kit.window.about" = {}
"omni.flux.feature_flags.window" = {}
"omni.flux.utils.common" = {}
"omni.ui" = {}
"omni.usd" = {}

[settings.exts."omni.flux.feature_flags.window"]
title = "Experimental Features"

[settings.exts."omni.flux.feature_flags.widget"]
label = "Enable or Disable Experimental Features:"

[settings.exts."omni.flux.feature_flags.widget".tree.headers]
0 = ""
1 = "Experimental Feature"

[[python.module]]
name = "lightspeed.trex.menu.workfile"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
