name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-windows.yml'

jobs:
  build-windows:
    runs-on: windows-2022

    steps:  
    - name: Build Windows
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        .\build.bat --rebuild --release
