name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-linux.yml'

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Linux
      shell: bash
      run: ./build.sh --rebuild --release
